# Generated by Django 5.0.9 on 2025-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprogress',
            name='category',
            field=models.CharField(choices=[('BUD', 'Budgeting'), ('INV', 'Investing'), ('SAV', 'Savings'), ('BAL', 'Balance Sheet'), ('CRD', 'Credit'), ('TAX', 'Taxes')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='questionprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
