# Generated by Django 5.1.1 on 2025-02-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0002_questionprogress_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1),
        ),
    ]
