# Generated by Django 5.1.1 on 2025-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0003_multiplechoice_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='category',
            field=models.CharField(choices=[('BUD', 'Budgeting'), ('INV', 'Investing'), ('SAV', 'Savings'), ('BAL', 'Balance Sheet'), ('CRD', 'Credit'), ('TAX', 'Taxes')], max_length=100),
        ),
    ]
