# Generated by Django 5.1.1 on 2025-03-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0005_cap_ace_user_balance_sheet_xp_cap_ace_user_budget_xp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback', models.TextField()),
                ('essential', models.BooleanField(default=False)),
                ('BudgetSimulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cap_ace_web.budgetsimulation')),
            ],
        ),
    ]
