# Generated by Django 5.1.1 on 2025-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0009_flashcard_fillintheblank_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsimulation',
            name='category',
            field=models.CharField(choices=[('BUD', 'Budgeting'), ('INV', 'Investing'), ('SAV', 'Savings'), ('BAL', 'Balance Sheet'), ('CRD', 'Credit'), ('TAX', 'Taxes')], default='BUD', max_length=3, null=True),
        ),
    ]
