# Generated by Django 5.0.9 on 2025-04-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0011_alter_expense_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAndDrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('category', models.CharField(choices=[('BUD', 'Budgeting'), ('INV', 'Investing'), ('SAV', 'Savings'), ('BAL', 'Balance Sheet'), ('CRD', 'Credit'), ('TAX', 'Taxes')], max_length=3, null=True)),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('feedback', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_definitions', to='cap_ace_web.matchanddrag')),
            ],
        ),
    ]
