# Generated by Django 5.1.1 on 2025-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0012_matchanddrag_termsanddefinitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=512),
        ),
    ]
