# Generated by Django 5.1.6 on 2025-04-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0013_alter_flashcard_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillInTheBlank',
        ),
    ]
