# Generated by Django 5.1.6 on 2025-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_ace_web', '0014_delete_fillintheblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('feedback', models.TextField(default='')),
                ('category', models.CharField(choices=[('BUD', 'Budgeting'), ('INV', 'Investing'), ('SAV', 'Savings'), ('BAL', 'Balance Sheet'), ('CRD', 'Credit'), ('TAX', 'Taxes')], max_length=3, null=True)),
                ('missing_word', models.CharField(max_length=100)),
            ],
        ),
    ]
